# Generated by Django 3.1.7 on 2021-02-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('ended_on', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(choices=[('PEN', 'PENDING'), ('IPR', 'IN_PROGRESS'), ('YAY', 'SUCCESSFUL'), ('BOO', 'FAILED')], default='PEN', max_length=4)),
                ('current', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=10)),
                ('description', models.CharField(blank=True, default='', max_length=128)),
                ('message', models.CharField(blank=True, default='', max_length=128)),
            ],
        ),
    ]
