# Generated by Django 3.1.7 on 2021-02-21 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProteinSearchJobManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProteinSearchJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.TextField()),
                ('record_found', models.CharField(blank=True, default='', max_length=1024)),
                ('record_description', models.TextField(blank=True, default='')),
                ('record_source', models.CharField(blank=True, default='', max_length=1024)),
                ('protein_id', models.CharField(blank=True, default='', max_length=128)),
                ('location_start', models.IntegerField(default=-1)),
                ('location_end', models.IntegerField(default=-1)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protein_searches', to='jobs.job')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protein_searches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
