# Generated by Django 3.1.7 on 2021-02-21 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('protein_search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProteinDatabaseEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=1024)),
                ('content', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='ProteinSearchJobManager',
        ),
        migrations.AlterField(
            model_name='proteinsearchjob',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='protein_searches', to='jobs.job'),
        ),
    ]
